[project]
name = "audio-prepare-pipeline-redo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tungnl5", email = "nguyenlamtung2005@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bs-roformer-infer",
    "datasets>=5.0.1",
    "demucs>=4.0.1",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "librosa>=0.11.0",
    "matplotlib>=3.11.1",
    "melband-roformer-infer",
    "numpy>=2.4.6",
    "onnxruntime-gpu>=1.20.0",
    "opencv-python-headless>=4.10.0",
    "pip>=26.2.1",
    "pyannote.audio",
    "python-dotenv>=1.0.0",
    "python-speech-features>=0.6",
    "soundfile>=0.14.0",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchcodec>=0.15.0",
    "yt-dlp>=2026.8.4.234419.dev0",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[tool.uv.sources]
bs-roformer-infer = { git = "https://github.com/openmirlab/bs-roformer-infer.git" }
melband-roformer-infer = { git = "https://github.com/openmirlab/melband-roformer-infer.git" }
